Fixing issue with non-existent variable.
Noticed the use of the wrong variable name (plural versus singular), which causes the entire tool to not function.

Error before fixing when running any 'git hub' commands:
NameError: global name 'hosts' is not defined